package com.solerforge.lumeria.database

import com.solerforge.lumeria.data.WorldLocation

object WorldDatabase {
    val locations = listOf(
        WorldLocation(
            name = "Training Fields",
            description = "A safe place for new adventurers.",
            levelRange = "Lv 1-5",
            minLevel = 1,
            maxLevel = 5,
            enemies = listOf("Slime", "Training Goblin", "Wild Rat", "Small Spider", "Stray Dog", "Aggressive Rooster", "Field Snake", "Wood Beetle"),
            boss = "Training Captain",
            bossUnlocked = true,
            x = 0.5f,
            y = 0.75f,
            requiredLevel = 1,
        ),
        WorldLocation(
            name = "Goblin Forest",
            description = "A dense forest filled with goblins.",
            levelRange = "Lv 6-15",
            minLevel = 6,
            maxLevel = 15,
            enemies = listOf("Goblin", "Goblin Archer", "Goblin Rogue", "Forest Spider", "Wild Boar", "Angry Wasp", "Wolf Pup", "Entling"),
            boss = "Goblin King",
            bossUnlocked = true,
            x = 0.25f,
            y = 0.6f,
            requiredLevel = 6,
        ),
        WorldLocation(
            name = "Crystal Caverns",
            description = "Sparkling caves filled with crystal creatures.",
            levelRange = "Lv 16-25",
            minLevel = 16,
            maxLevel = 25,
            enemies = listOf("Crystal Slime", "Cave Bat", "Crystal Spider", "Gem Crawler", "Rock Worm", "Stalactite Mimic", "Echo Bat", "Crystal Scorpion"),
            boss = "Crystal Guardian",
            bossUnlocked = true,
            x = 0.75f,
            y = 0.45f,
            requiredLevel = 16,
        ),
        WorldLocation(
            name = "Stonehold Pass",
            description = "A dangerous mountain pass.",
            levelRange = "Lv 26-35",
            minLevel = 26,
            maxLevel = 35,
            enemies = listOf("Orc", "Stone Golem", "Mountain Wolf", "Orc Grunt", "Harpy", "Mountain Hawk", "Rock Slide Golem", "Iron Boar"),
            boss = "Stone Titan",
            bossUnlocked = true,
            x = 0.75f,
            y = 0.7f,
            requiredLevel = 26,
        ),
        WorldLocation(
            name = "Shadow Marsh",
            description = "A dark swamp haunted by spirits.",
            levelRange = "Lv 36-50",
            minLevel = 36,
            maxLevel = 50,
            enemies = listOf("Poison Toad", "Dark Spirit", "Swamp Horror", "Leech", "Marsh Stalker", "Dread Mosquito", "Shade", "Will-o'-the-Wisp"),
            boss = "Marsh Horror",
            bossUnlocked = true,
            x = 0.5f,
            y = 0.25f,
            requiredLevel = 36,
        ),
        WorldLocation(
            name = "Dragon Peaks",
            description = "Volcanic mountains ruled by dragons.",
            levelRange = "Lv 51-65",
            minLevel = 51,
            maxLevel = 65,
            enemies = listOf("Fire Drake", "Stone Golem", "Lava Serpent", "Peak Wyvern", "Magma Slime", "Cinder Elemental", "Volcanic Turtle", "Ash Griffin"),
            boss = "Ancient Dragon",
            bossUnlocked = true,
            x = 0.25f,
            y = 0.3f,
            requiredLevel = 51,
        ),
        WorldLocation(
            name = "Dark Citadel",
            description = "The stronghold of Xious' greatest enemy.",
            levelRange = "Lv 66-75",
            minLevel = 66,
            maxLevel = 75,
            enemies = listOf("Dark Spirit", "Shadow Knight", "Void Reaper", "Void Hound", "Citadel Guard", "Shadow Assassin", "Cursed Armor", "Wicked Gargoyle"),
            boss = "Lord Xarthos",
            bossUnlocked = true,
            x = 0.8f,
            y = 0.2f,
            requiredLevel = 66,
        ),
    )

    val legacyLocations = listOf(
        WorldLocation(
            name = "Celestial Plains",
            description = "A radiant expanse where the ground glows with starlight.",
            levelRange = "Lv 1-20",
            minLevel = 1,
            maxLevel = 20,
            enemies = listOf("Astral Slime", "Star-Gazer Rabbit", "Sky-Fin Hawk", "Cloud-Singer", "Meteor Beetle", "Nova Sprite", "Solar Hound", "Lunar Fox", "Celestial Lamb", "Dawn-Bringer"),
            boss = "The Star Sovereign",
            bossUnlocked = true,
            x = 0.5f,
            y = 0.85f,
            requiredLevel = 1,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Ancient Arboretum",
            description = "A forest of colossal trees that remember the dawn of time.",
            levelRange = "Lv 21-40",
            minLevel = 21,
            maxLevel = 40,
            enemies = listOf("Root-Walker", "Leaf-Blade Mantis", "Elder Treant", "Blossom Spirit", "Thistle-Back Boar", "Vine-Wrapper", "Spore-Spitter", "Arboretum Owl", "Moss-Guard", "Grove Warden"),
            boss = "The Ancient Oak",
            bossUnlocked = true,
            x = 0.2f,
            y = 0.7f,
            requiredLevel = 21,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Prismatic Depths",
            description = "Caves where light refracts into a thousand deadly colors.",
            levelRange = "Lv 41-60",
            minLevel = 41,
            maxLevel = 60,
            enemies = listOf("Quartz Golem", "Emerald Crawler", "Ruby Wasp", "Sapphire Serpent", "Amethyst Bat", "Diamond Weaver", "Prismatic Leech", "Echo-Shard", "Crystal-Eye", "Depth-Stalker"),
            boss = "Prismatic Queen",
            bossUnlocked = true,
            x = 0.8f,
            y = 0.6f,
            requiredLevel = 41,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Ironbound Peaks",
            description = "Mountains forged from unbreakable celestial iron.",
            levelRange = "Lv 61-80",
            minLevel = 61,
            maxLevel = 80,
            enemies = listOf("Steel-Horn Goat", "Peak Sentinel", "Sky-Render Griffin", "Iron-Claw Eagle", "Thunder-Hoof", "Frost-Giant Scout", "Peak Marauder", "Storm-Wing", "Rock-Slider", "Mountain Giant"),
            boss = "The Iron Titan",
            bossUnlocked = true,
            x = 0.7f,
            y = 0.4f,
            requiredLevel = 61,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Eternal Fen",
            description = "A swamp that exists in a state of perpetual dusk.",
            levelRange = "Lv 81-100",
            minLevel = 81,
            maxLevel = 100,
            enemies = listOf("Gloom-Wisp", "Bog-Behemoth", "Fen-Wraith", "Mist-Stalker", "Corrupted Toad", "Shadow-Croc", "Weeping Willow", "Fen-Lurker", "Rot-Gnat", "Swamp Sovereign"),
            boss = "Fen Horror",
            bossUnlocked = true,
            x = 0.3f,
            y = 0.3f,
            requiredLevel = 81,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Solaris Volcano",
            description = "A volcano that burns with the heat of a captured sun.",
            levelRange = "Lv 101-120",
            minLevel = 101,
            maxLevel = 120,
            enemies = listOf("Magma-Core Golem", "Ember-Drake", "Solar Flare", "Obsidian Beetle", "Fire-Ant Drone", "Ash-Spirit", "Volcanic Charger", "Heat-Seeker", "Cinder-Bat", "Inferno Wyrm"),
            boss = "Solaris Drake",
            bossUnlocked = true,
            x = 0.1f,
            y = 0.2f,
            requiredLevel = 101,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Abyssal Spire",
            description = "A tower that pierces the very fabric of the void.",
            levelRange = "Lv 121-140",
            minLevel = 121,
            maxLevel = 140,
            enemies = listOf("Void-Walker", "Soul-Harvester", "Spire-Guard", "Darkness-Elemental", "Abyssal Eye", "Shadow-Stalker", "Spire-Wraith", "Void-Leech", "Terror-Bringer", "Spire-Lord"),
            boss = "Abyssal Magister",
            bossUnlocked = true,
            x = 0.9f,
            y = 0.1f,
            requiredLevel = 121,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "The Floating Isles",
            description = "Islands suspended by ancient arcane ley lines.",
            levelRange = "Lv 141-155",
            minLevel = 141,
            maxLevel = 155,
            enemies = listOf("Sky-Whale", "Wind-Dancer", "Thunder-Bird", "Gale-Spirit", "Island-Hopper", "Cloud-Whale", "Storm-Giant", "Aerial-Assassin", "Sky-Serpent", "Zephyr-Blade"),
            boss = "Grand Zephyr",
            bossUnlocked = true,
            x = 0.5f,
            y = 0.05f,
            requiredLevel = 141,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Sunken City of Lumeria",
            description = "The ruins of the old capital, now beneath the waves.",
            levelRange = "Lv 156-170",
            minLevel = 156,
            maxLevel = 170,
            enemies = listOf("Deep-Sea Horror", "Sunken Guard", "Coral-Reaper", "Tide-Caller", "Abyss-Fish", "Drowned-Soul", "Sea-Dragon", "Kelp-Tangler", "Pearl-Guardian", "Neptune's Shadow"),
            boss = "The Deep One",
            bossUnlocked = true,
            x = 0.2f,
            y = 0.5f,
            requiredLevel = 156,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Valley of Echoes",
            description = "A place where the past and future overlap.",
            levelRange = "Lv 171-185",
            minLevel = 171,
            maxLevel = 185,
            enemies = listOf("Memory-Ghost", "Echo-Spirit", "Time-Thief", "Past-Warrior", "Future-Sentinel", "Mirage-Stalker", "Sound-Weaver", "Valley-Banshee", "Whispering-Shadow", "Echo-Master"),
            boss = "Chronos",
            bossUnlocked = true,
            x = 0.7f,
            y = 0.1f,
            requiredLevel = 171,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Frozen Tundra of Fate",
            description = "A wasteland of ice where destiny is decided.",
            levelRange = "Lv 186-195",
            minLevel = 186,
            maxLevel = 195,
            enemies = listOf("Frost-Wolf", "Tundra-Yeti", "Ice-Wraith", "Glacial-Golem", "Snow-Stalker", "Cold-Snap Sprite", "Tundra-Scout", "Blizzard-Beast", "Ice-Drake", "Fate-Weaver"),
            boss = "The Fate Binder",
            bossUnlocked = true,
            x = 0.4f,
            y = 0.1f,
            requiredLevel = 186,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "The Genesis Nexus",
            description = "The origin point of all existence in Lumeria.",
            levelRange = "Lv 196-200",
            minLevel = 196,
            maxLevel = 200,
            enemies = listOf("Reality-Warp", "Origin-Spirit", "Nexus-Guard", "Creation-Spawn", "Destruction-Echo", "Alpha-Omega", "Infinite-Serpent", "Nexus-Core", "Primordial-Force", "The First Thought"),
            boss = "The Genesis Creator",
            bossUnlocked = true,
            x = 0.5f,
            y = 0.0f,
            requiredLevel = 196,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "Demonic Abyss",
            description = "A bottomless pit of pure evil.",
            levelRange = "Lv 100-150",
            minLevel = 100,
            maxLevel = 150,
            enemies = listOf("Lesser Demon", "Abyssal Imp", "Hellhound", "Shadow Fiend", "Brimstone Golem", "Void Horror", "Chaos Spawn", "Demon Warrior"),
            boss = "Abyssal Lord",
            bossUnlocked = true,
            x = 0.1f,
            y = 0.1f,
            requiredLevel = 100,
            isLegacyOnly = true
        ),
        WorldLocation(
            name = "The Underworld",
            description = "The realm of the dead.",
            levelRange = "Lv 151-200",
            minLevel = 151,
            maxLevel = 200,
            enemies = listOf("Skeleton Knight", "Wraith", "Lich Apprentice", "Ghostly Dragon", "Death Weaver", "Soul Eater", "Underworld Cerberus", "Ethereal Horror"),
            boss = "Hades' Shadow",
            bossUnlocked = true,
            x = 0.9f,
            y = 0.9f,
            requiredLevel = 150,
            isLegacyOnly = true
        )
    )

    fun getLocation(name: String): WorldLocation {
        val virtualLocations = mapOf(
            "Grand Arena" to WorldLocation("Grand Arena", "The ultimate stage for warriors.", "Lv 1-100", 1, 100, emptyList(), "", x=0f, y=0f, requiredLevel = 1),
            "Tower of Trials" to WorldLocation("Tower of Trials", "A test of infinite ascension.", "Lv 80-200", 80, 200, emptyList(), "", x=0f, y=0f, requiredLevel = 80),
            "Fire Exam" to WorldLocation("Fire Exam", "Trial of the House of Fire.", "Lv 1-100", 1, 100, emptyList(), "", x=0f, y=0f, requiredLevel = 1),
            "Water Exam" to WorldLocation("Water Exam", "Trial of the House of Water.", "Lv 1-100", 1, 100, emptyList(), "", x=0f, y=0f, requiredLevel = 1),
            "Wind Exam" to WorldLocation("Wind Exam", "Trial of the House of Wind.", "Lv 1-100", 1, 100, emptyList(), "", x=0f, y=0f, requiredLevel = 1),
            "The Eternal Realm" to WorldLocation("The Eternal Realm", "A place beyond time.", "Lv 100", 100, 100, emptyList(), "", x=0f, y=0f, requiredLevel = 100)
        )
        return (locations + legacyLocations + MonsterWorldDatabase.locations).find { it.name == name }
            ?: virtualLocations[name]
            ?: error("Unknown location: $name")
    }
}
