package com.example.lumeria.database

import com.example.lumeria.data.WorldLocation

object WorldDatabase {
    val locations = listOf(
        WorldLocation(
            name = "Training Fields",
            description = "A safe place for new adventurers.",
            levelRange = "Lv 1-5",
            minLevel = 1,
            maxLevel = 5,
            enemies = listOf("Slime", "Training Goblin", "Wild Rat", "Small Spider", "Stray Dog", "Aggressive Rooster", "Field Snake", "Wood Beetle"),
            boss = "Training Captain",
            bossUnlocked = true,
            x = 0.5f,
            y = 0.75f,
            requiredLevel = 1,
        ),
        WorldLocation(
            name = "Goblin Forest",
            description = "A dense forest filled with goblins.",
            levelRange = "Lv 6-15",
            minLevel = 6,
            maxLevel = 15,
            enemies = listOf("Goblin", "Goblin Archer", "Goblin Rogue", "Forest Spider", "Wild Boar", "Angry Wasp", "Wolf Pup", "Entling"),
            boss = "Goblin King",
            bossUnlocked = true,
            x = 0.25f,
            y = 0.6f,
            requiredLevel = 6,
        ),
        WorldLocation(
            name = "Crystal Caverns",
            description = "Sparkling caves filled with crystal creatures.",
            levelRange = "Lv 16-25",
            minLevel = 16,
            maxLevel = 25,
            enemies = listOf("Crystal Slime", "Cave Bat", "Crystal Spider", "Gem Crawler", "Rock Worm", "Stalactite Mimic", "Echo Bat", "Crystal Scorpion"),
            boss = "Crystal Guardian",
            bossUnlocked = true,
            x = 0.75f,
            y = 0.45f,
            requiredLevel = 16,
        ),
        WorldLocation(
            name = "Stonehold Pass",
            description = "A dangerous mountain pass.",
            levelRange = "Lv 26-35",
            minLevel = 26,
            maxLevel = 35,
            enemies = listOf("Orc", "Stone Golem", "Mountain Wolf", "Orc Grunt", "Harpy", "Mountain Hawk", "Rock Slide Golem", "Iron Boar"),
            boss = "Stone Titan",
            bossUnlocked = true,
            x = 0.75f,
            y = 0.7f,
            requiredLevel = 26,
        ),
        WorldLocation(
            name = "Shadow Marsh",
            description = "A dark swamp haunted by spirits.",
            levelRange = "Lv 36-50",
            minLevel = 36,
            maxLevel = 50,
            enemies = listOf("Poison Toad", "Dark Spirit", "Swamp Horror", "Leech", "Marsh Stalker", "Dread Mosquito", "Shade", "Will-o'-the-Wisp"),
            boss = "Marsh Horror",
            bossUnlocked = true,
            x = 0.5f,
            y = 0.25f,
            requiredLevel = 36,
        ),
        WorldLocation(
            name = "Dragon Peaks",
            description = "Volcanic mountains ruled by dragons.",
            levelRange = "Lv 51-65",
            minLevel = 51,
            maxLevel = 65,
            enemies = listOf("Fire Drake", "Stone Golem", "Lava Serpent", "Peak Wyvern", "Magma Slime", "Cinder Elemental", "Volcanic Turtle", "Ash Griffin"),
            boss = "Ancient Dragon",
            bossUnlocked = true,
            x = 0.25f,
            y = 0.3f,
            requiredLevel = 25,
        ),
        WorldLocation(
            name = "Dark Citadel",
            description = "The stronghold of Xious' greatest enemy.",
            levelRange = "Lv 66-75",
            minLevel = 66,
            maxLevel = 75,
            enemies = listOf("Dark Spirit", "Shadow Knight", "Void Reaper", "Void Hound", "Citadel Guard", "Shadow Assassin", "Cursed Armor", "Wicked Gargoyle"),
            boss = "Lord Xarthos",
            bossUnlocked = true,
            x = 0.8f,
            y = 0.2f,
            requiredLevel = 66,
        )
    )
}
